services:
  # Popuniti u Dijelu 12 (SQL Server, RabbitMQ, API, Subscriber)
  # activetogether-db:
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  # activetogether-rabbitmq:
  #   image: rabbitmq:3.13-management
  # activetogether-api:
  #   build: ./ActiveTogether.WebAPI
  # activetogether-subscriber:
  #   build: ./ActiveTogether.Subscriber
